const ActionTypes = {
	FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
	FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
	FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
	ADD_SELECTED_PRODUCT: "ADD_SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
	TOGGLE_SHOW_DIFFERENCES: "TOGGLE_SHOW_DIFFERENCES",
};

export default ActionTypes;
